version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: myblog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 15800xht
      MYSQL_DATABASE: myblog
      MYSQL_USER: myblog
      MYSQL_PASSWORD: myblog123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - myblog-network

  # Redis缓存（可选）
  redis:
    image: redis:7-alpine
    container_name: myblog-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - myblog-network

  # FastAPI应用
  app:
    build: .
    container_name: myblog-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://myblog:myblog123@mysql:3306/myblog
      - REDIS_URL=redis://redis:6379
      - DEBUG=false
    volumes:
      - ./static:/app/static
    depends_on:
      - mysql
      - redis
    networks:
      - myblog-network

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: myblog-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - app
    networks:
      - myblog-network

volumes:
  mysql_data:
  redis_data:

networks:
  myblog-network:
    driver: bridge